routes:
  /: home
  /sitemap/:
    template: sitemap
    content_type: text/xml

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
