name: Deploy Theme
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance:
          - instance1
          - instance2
          # Add more instances as needed
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ secrets[format('GHOST_ADMIN_API_URL_{0}', matrix.instance)] }}
          api-key: ${{ secrets[format('GHOST_ADMIN_API_KEY_{0}', matrix.instance)] }}
          theme-name: casper-multilingual